<div class="container-fluid">
    <div>
        <h3>Настройки партнерской программы</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Главная</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Пользователи</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Партнерская система</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Настройки партнерской программы</li>
            </ol>
        </nav>
    </div>
    <!-- Вертикальный макет -->
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Настройки партнерской программы</h6>
                    <div class="affiliates-settings-alert"></div>
                    <form class="affiliates-settings" method="POST">
						<div>
							<div class="float-left">
								<label for="affiliate_system" class="main-label">Партнерская система</label>
								<br><small class="admin-info">Пользователь будет зарабатывать деньги, приглашая пользователей на ваш сайт</small>
							</div>
							<div class="form-group float-right switcher">
								<input type="hidden" name="affiliate_system" value="0">
								<input type="checkbox" name="affiliate_system" id="affiliate_system-enabled" value="1" <?php echo ($wo['config']['affiliate_system'] == '1') ? 'checked': '';?>>
								<label for="affiliate_system-enabled" class="check-trail"><span class="check-handler"></span></label>
							</div>
							<div class="clearfix"></div>
							<hr>
						</div>
					
                        <label for="affiliate_type">Пользователь будет зарабатывать деньги, когда</label>
                        <select class="form-control show-tick" id="affiliate_type" name="affiliate_type">
                            <option value="0" <?php echo ($wo['config']['affiliate_type'] == 0) ? 'selected': '';?> >Новый пользователь зарегистрируется</option>
                            <option value="1" <?php echo ($wo['config']['affiliate_type'] == 1) ? 'selected': '';?> >Новый пользователь зарегистрируется и купит PRO пакет / кредиты</option>
                        </select>
						<small class="admin-info">Пользователь будет зарабатывать деньги от партнерской программы</small>
                        <div class="clearfix"></div>
                        <div class="form-group form-float amount_ref">
                            <div class="form-line">
                                <label class="form-label">Сумма</label>
                                <input type="text" id="amount_ref" name="amount_ref" class="form-control" value="<?php echo $wo['config']['amount_ref']?>">
								<small class="admin-info">Цена, которую вы заплатите за каждого нового пользователя. По умолчанию 0.10</small>
                            </div>
                        </div>
                        <div class="form-group form-float amount_percent_ref">
                            <div class="form-line">
                                <label class="form-label">Процент</label>
                                <input type="number" min="0" max="100" id="amount_percent_ref" name="amount_percent_ref" class="form-control" value="<?php echo $wo['config']['amount_percent_ref']?>">
								<small class="admin-info">Процент от суммы, которую вы заплатите за нового пользователя после покупки любого PRO пакета.</small>
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- Конец вертикального макета -->
    <script>
        $(document).ready(function() {
            $('#amount_ref').focus(function() { $(this).select(); } );
            $('#amount_percent_ref').focus(function() { $(this).select(); } );
        });
        $(function() {

            // Убедиться, что значение в пределах 0-100
            $('#amount_percent_ref').keyup(function(e) {
                var num = $(this).val();
                if(isNaN(num)||num<0 ||num>100) {
                    alert("Введите число от 0 до 100");
                    $(this).val("0");
                }

                $('#amount_ref').val(0);
            });

            $('#amount_ref').keyup(function(e) {
                var num = $(this).val();
                if(isNaN(num)||num<0) {
                    alert("Введите только число");
                    $(this).val("0");
                }

                $('#amount_percent_ref').val(0);
            });

            //to hide and show inputs according to selected value
            // $('#affiliate_type').change(function(e){
            //     var selected_affiliate_type = $('#affiliate_type :selected').text();
            //     if( selected_affiliate_type == "New user is registred" ){
            //         $('.amount_ref').show();
            //         $('.amount_percent_ref').hide();
            //     }else if( selected_affiliate_type == "New user is registred & bought a pro package" ){
            //         $('.amount_ref').hide();
            //         $('.amount_percent_ref').show();
            //     }
            // });
        });
$(function() {
    $('.switcher input[type=checkbox]').click(function () {
        var configName = $(this).attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        if ($(this).is(":checked") === true) {
            objData[configName] = $(this).val();
        }
        else{
            if ($('input[name='+configName+']')[0]) {
                objData[configName] = $($('input[name='+configName+']')[0]).val();
            }
        }
        objData['hash_id'] = hash_id;
        $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData);
    });

    var setTimeOutColor = setTimeout(function (){});
    $('select').on('change', function() {
         clearTimeout(setTimeOutColor);
        var thisElement = $(this);
        var configName = thisElement.attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        objData[configName] = this.value;
        objData['hash_id'] = hash_id;
        thisElement.addClass('warning');
        $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function (data) {
            if (data.status == 200) {
                thisElement.removeClass('warning');
                thisElement.addClass('success');
            } else {
                thisElement.addClass('error');
            }
            var setTimeOutColor = setTimeout(function () {
                thisElement.removeClass('success');
                thisElement.removeClass('warning');
                thisElement.removeClass('error');
            }, 2000);
        });
    });
    $('input[type=text], input[type=number], input[type=password], textarea').on('input', delay(function() {
            clearTimeout(setTimeOutColor);
            var thisElement = $(this);
            var configName = thisElement.attr('name');
            var hash_id = $('input[name=hash_id]').val();
            var objData = {};
            objData[configName] = this.value;
            objData['hash_id'] = hash_id;
            thisElement.addClass('warning');
            $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function (data) {
                if (data.status == 200) {
                    thisElement.removeClass('warning');
                    thisElement.addClass('success');
                } else {
                    thisElement.addClass('error');
                }
                var setTimeOutColor = setTimeout(function () {
                    thisElement.removeClass('success');
                    thisElement.removeClass('warning');
                    thisElement.removeClass('error');
                }, 2000);
                //thisElement.focus();
            });
    }, 500));
});
    </script>