<div class="container-fluid">
    <div>
        <h3>Автоматический лайк пользователей</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Главная</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Инструменты</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Автоматический лайк пользователей</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Автоматический лайк пользователей</h6>
                    <div class="alert alert-info">Когда пользователь создаёт новый аккаунт, выберите, какие пользователи должны автоматически поставить лайк.</div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Пользователи страницы, разделённые запятой (,)</label>
                                <input type="text" id="users" name="users" class="form-control" value="<?php echo $wo['config']['auto_user_like']; ?>">
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <small>Этот процесс может занять некоторое время, вы можете проверить изменения на вашем сайте через несколько минут.</small>
                        <div class="clearfix"></div>
                        <br>
                  <button type="submit" class="btn btn-danger waves-effect waves-light m-t-20" id="users-btn">Сохранить</button>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<script>
$(document).on('click', '#users-btn', function(event) {
	event.preventDefault();
	$(this).text('Пожалуйста, подождите...');
	$.get(Wo_Ajax_Requests_File(), {f:'admin_setting', s: 'auto_user_like', users: $('#users').val()}, function(data, textStatus, xhr) {
		$('#users-btn').text('Сохранено!');
		setTimeout(function () {
			$('#users-btn').text('Сохранить');
		}, 4000);
	});
});
</script>
