<div class="container-fluid">
    <div>
        <h3>Управление страницами условий</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Главная</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Страницы</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Управление страницами условий</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Управление страницами условий</h6>
                    <div class="langs-settings-alert"></div>
                   <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover" style="table-layout: inherit; border-top: 1px solid;">
                            <thead>
                                <tr>
                                    <th style="text-align: center;">Название страницы</th>
                                    <th style="text-align: center;">Действие</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="setting-postlist">
                                   <td style="text-align: center;">Условия использования</td>
                                   <td style="text-align: center;">
                                      <a class="btn bg-success admn_table_btn" href="<?php echo Wo_LoadAdminLinkSettings('edit-terms-pages?type=terms_of_use_page');?>">Редактировать</a>
                                   </td>
                                </tr>
                                <tr class="setting-postlist">
                                   <td style="text-align: center;">Политика конфиденциальности</td>
                                   <td style="text-align: center;">
                                      <a class="btn bg-success admn_table_btn" href="<?php echo Wo_LoadAdminLinkSettings('edit-terms-pages?type=privacy_policy_page');?>">Редактировать</a>
                                   </td>
                                </tr>
                                <tr class="setting-postlist">
                                   <td style="text-align: center;">О нас</td>
                                   <td style="text-align: center;">
                                      <a class="btn bg-success admn_table_btn" href="<?php echo Wo_LoadAdminLinkSettings('edit-terms-pages?type=about_page');?>">Редактировать</a>
                                   </td>
                                </tr>
                                <tr class="setting-postlist">
                                   <td style="text-align: center;">Возврат средств</td>
                                   <td style="text-align: center;">
                                      <a class="btn bg-success admn_table_btn" href="<?php echo Wo_LoadAdminLinkSettings('edit-terms-pages?type=refund_terms_page');?>">Редактировать</a>
                                   </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
