<div class="container-fluid">
    <div>
        <h3>Создать новую пользовательскую страницу</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Главная</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Страницы</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Создать новую пользовательскую страницу</li>
            </ol>
        </nav>
    </div>
    <!-- Вертикальная компоновка -->
    <div class="row">
        <div class="col-lg-8 col-md-8">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Создать новую пользовательскую страницу</h6>
                    <div class="add-settings-alert"></div>
                    <form class="add-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Имя страницы <small><?php echo $wo['config']['site_url'] . '/page/PAGE_NAME'?></small></label>
                                <input type="text" id="page_name" name="page_name" class="form-control">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Заголовок страницы <small>Название страницы, которое будет отображаться в футере</small></label>
                                <input type="text" id="page_title" name="page_title" class="form-control">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Содержимое страницы <small>Содержимое страницы (разрешён HTML)</small></label>
                                <textarea name="page_content" id="page_content" class="form-control" cols="30" rows="5"></textarea>
                            </div>
                        </div>
                        <label for="page_type">Тип страницы</label>
                        <select class="form-control show-tick" id="page_type" name="page_type">
                            <option value="1">С фоном и заголовком</option>
                            <option value="0">Пустая страница</option>
                        </select>
                        <div class="clearfix"></div>
                        <br>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Создать</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #КОНЕЦ# Вертикальная компоновка -->
<script>
$(function() {
    var form_add_settings = $('form.add-settings');
    form_add_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=add_new_page&p=manage-custom-pages',
        beforeSend: function() {
            form_add_settings.find('.waves-effect').text('Пожалуйста, подождите..');
        },
        success: function(data) {
            if (data.status == 200) {
                $("html, body").animate({ scrollTop: 0 }, "slow");
                $('.add-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Страница успешно добавлена</div>');
                setTimeout(function () {
		            window.location.href = '<?php echo Wo_LoadAdminLinkSettings('manage-custom-pages'); ?>';
		        }, 1000);
            } else if (data.status == 400) {
	          $('.add-settings-alert').html('<div class="alert alert-danger">'+data.message+'</div>');
                        setTimeout(function () {
                            $('.add-settings-alert').empty();
                        }, 2000);
	        }
	        form_add_settings.find('.waves-effect').text('Создать');
        }
    });
});
</script>
