<div class="container-fluid">
    <div>
        <h3>Создать новое пользовательское поле</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Главная</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Пользователи</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Создать новое пользовательское поле</li>
            </ol>
        </nav>
    </div>
    <!-- Вертикальная раскладка -->
    <div class="row">
        <div class="col-lg-8 col-md-8">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Создать новое пользовательское поле</h6>
                    <div class="add-settings-alert"></div>
                    <div class="help-block">Используйте {{LANG lang_variable}} для перевода данных поля. Например: {{LANG first_name}}</div><br>
                    <form class="add-settings" method="POST">
                        <label for="type">Тип поля</label>
                        <select class="form-control show-tick chosen-select" id="type" name="type">
                          <option value="textbox">Текстовое поле</option>
                          <option value="textarea">Текстовая область</option>
                          <option value="selectbox">Выпадающий список</option>
                        </select>
                        <div class="clearfix"></div>
                        <br>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Название поля</label>
                                <input type="text" id="name" name="name" class="form-control">
                            </div>
                        </div>
                       
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Длина поля: <small>Значение по умолчанию — 32, максимальное значение — 1000</small></label>
                                <input type="text" id="length" name="length" class="form-control" value="32">
                            </div>
                        </div>
                         <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Описание поля: <small>Описание будет отображаться под полем</small></label>
                                <textarea name="description" id="description" class="form-control" cols="30" rows="3"></textarea>
                            </div>
                        </div>
                        <label for="placement">Расположение поля</label>
                        <select class="form-control show-tick " id="placement" name="placement">
                         <option value="general">Общие настройки</option>
                         <option value="profile">Настройки профиля</option>
                         <option value="social">Социальные ссылки</option>
                         <option value="none">Не отображать поле на странице настроек</option>
                        </select>
                        <div class="clearfix"></div>
                        <br><!--
                        <label for="registration_page">Показывать на странице регистрации</label>
                        <select class="form-control show-tick" id="registration_page" name="registration_page">
                         		<option value="0" selected>Нет</option>
                 				<option value="1">Да</option>
                        </select>-->
                        <div class="clearfix"></div>
                        <br>
                        <label for="profile_page">Показывать на странице профиля пользователя</label>
                        <select class="form-control show-tick" id="profile_page" name="profile_page">
                         		<option value="0" selected>Нет</option>
                 				<option value="1">Да</option>
                        </select>
                        <div class="clearfix"></div>
                        <br><br>
                        <div class="form-group form-float options" style="display:none">
                            <div class="form-line">
                                <label class="form-label">Опции для выпадающего списка: <small>Одна опция на строку.</small></label>
                                <textarea name="options" id="options" class="form-control" cols="30" rows="3"></textarea>
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Создать</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #КОНЕЦ# Вертикальная раскладка -->
<script>
$(function() {
	$('.chosen-select').on('change', function(evt, params) {
       var selectedValue = $(this).val();
       if (selectedValue == 'selectbox') {
       	  $('.options').fadeIn(200);
       } else {
       	  $('.options').fadeOut(200);
       }
   });
});

$(function() {
    var form_add_settings = $('form.add-settings');
    form_add_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=add_new_field&p=manage-profile-fields',
        beforeSend: function() {
            form_add_settings.find('.waves-effect').text('Пожалуйста, подождите...');
        },
        success: function(data) {
            if (data.status == 200) {
                $("html, body").animate({ scrollTop: 0 }, "slow");
                $('.add-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Поле успешно добавлено</div>');
                setTimeout(function () {
		            window.location.href = '<?php echo Wo_LoadAdminLinkSettings('manage-profile-fields'); ?>';
		        }, 1000);
            } else if (data.status == 400) {
                $('.add-settings-alert').html('<div class="alert alert-danger">'+data.message+'</div>');
                setTimeout(function () {
                    $('.add-settings-alert').empty();
                }, 2000);
	        }
	        form_add_settings.find('.waves-effect').text('Создать');
        }
    });
});
</script>
