<?php
if (empty($_GET['id'])) {
    header("Location: " . $wo['config']['site_url']);
    exit();
}
$field = GetFieldData($_GET['id']);
if (empty($field)) {
    header("Location: " . $wo['config']['site_url']);
    exit();
}
?>
<div class="container-fluid">
    <div>
        <h3>Редактирование пользовательского поля</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Главная</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Пользователи</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Редактирование пользовательского поля</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-8 col-md-8">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Редактирование пользовательского поля #<?php echo $_GET['id'] ?></h6>
                    <div class="add-settings-alert"></div>
                    <form class="add-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Название поля</label>
                                <input type="text" id="name" name="name" class="form-control" value="<?php echo $field['name']?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Длина поля: <small>По умолчанию значение 32, максимум 1000</small></label>
                                <input type="text" id="length" name="length" class="form-control" value="<?php echo $field['length']?>">
                            </div>
                        </div>
                         <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Описание поля: <small>Описание будет отображаться под полем</small></label>
                                <textarea name="description" id="description" class="form-control" cols="30" rows="3"><?php echo $field['description']?></textarea>
                            </div>
                        </div>
                        <label for="placement">Расположение поля</label>
                        <select class="form-control show-tick " id="placement" name="placement">
                         	<option value="general" <?php echo ($field['placement'] == 'general') ? 'selected': '';?>>Общие настройки</option>
		                 	<option value="profile" <?php echo ($field['placement'] == 'profile') ? 'selected': '';?>>Настройки профиля</option>
		                 	<option value="social" <?php echo ($field['placement'] == 'social') ? 'selected': '';?>>Социальные ссылки</option>
		                 	<option value="none" <?php echo ($field['placement'] == 'none') ? 'selected': '';?>>Не показывать поле на странице настроек</option>
                        </select>
                        <div class="clearfix"></div>
                        <br>
                        <label for="profile_page">Показать на странице профиля пользователя</label>
                        <select class="form-control show-tick" id="profile_page" name="profile_page">
                         		<option value="0" <?php echo ($field['profile_page'] == '0') ? 'selected': '';?>>Нет</option>
                  				<option value="1" <?php echo ($field['profile_page'] == '1') ? 'selected': '';?>>Да</option>
                        </select>
                        <div class="clearfix"></div>
                        <br>
                        <label for="active">Активно</label>
                        <select class="form-control show-tick" id="active" name="active">
                         		<option value="0" <?php echo ($field['active'] == '0') ? 'selected': '';?>>Нет</option>
                 				 <option value="1" <?php echo ($field['active'] == '1') ? 'selected': '';?>>Да</option>
                        </select>
                        <div class="clearfix"></div>
                        <br><br>
                        <?php if ($field['select_type'] == 'yes') { ?>
                        <div class="form-group form-float options">
                            <div class="form-line">
                                <label class="form-label">Опции для выпадающего списка: <small>Одна опция на строку.</small></label>
                                <textarea name="options" id="options" class="form-control" cols="30" rows="3"><?php echo str_replace(',', "\n", $field['type'])?></textarea>
                            </div>
                        </div>
                        <?php } ?>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <input type="hidden" name="id" value="<?php echo $field['id'];?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>
$(function() {
	$('.chosen-select').on('change', function(evt, params) {
       var selectedValue = $(this).val();
       if (selectedValue == 'selectbox') {
       	  $('.options').fadeIn(200);
       } else {
       	  $('.options').fadeOut(200);
       }
   });
});

$(function() {
    var form_add_settings = $('form.add-settings');
    form_add_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=edit_field&p=manage-profile-fields',
        beforeSend: function() {
            form_add_settings.find('.waves-effect').text('Пожалуйста, подождите..');
        },
        success: function(data) {
            if (data.status == 200) {
                $("html, body").animate({ scrollTop: 0 }, "slow");
                $('.add-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Поле успешно отредактировано</div>');
                setTimeout(function () {
		            window.location.href = '<?php echo Wo_LoadAdminLinkSettings('manage-profile-fields'); ?>';
		        }, 1000);
            } else if (data.status == 400) {
                $('.add-settings-alert').html('<div class="alert alert-danger">'+data.message+'</div>');
                setTimeout(function () {
                    $('.add-settings-alert').empty();
                }, 2000);
	        }
	        form_add_settings.find('.waves-effect').text('Сохранить');
        }
    });
});
</script>
