<div class="container-fluid">
    <div>
        <h3>Генератор фейковых пользователей</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Главная</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Инструменты</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Генератор фейковых пользователей</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <form action="" method="POST" class="generate-form">
                    <div class="card-body">
                        <h6 class="card-title">Генератор фейковых пользователей</h6>
                        <div class="alert alert-info">Генерируйте неограниченное количество фейковых пользователей.</div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Сколько пользователей вы хотите создать?</label>
                                <input type="number" id="count_users" name="count_users" class="form-control" value="10" min="10">
                                <small class="admin-info">Минимальное количество пользователей — 10</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Пароль</label>
                                <input type="text" id="password" name="password" class="form-control">
                                <small class="admin-info">Выберите пароль, который будет использоваться для всех пользователей. По умолчанию: 123456789</small>
                            </div>
                        </div>
                        <label for="avatar">Создать случайный аватар?</label>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="avatar" id="avatar-enabled" value="1">
                                <label class="form-check-label" for="avatar-enabled">Да</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="avatar" id="avatar-disabled" value="0" checked>
                                <label class="form-check-label" for="avatar-disabled" class="m-l-20">Нет</label>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <small>Если включен аватар, возможно появление дублированных аватаров, так как они создаются случайным образом.</small><br>
                        <small>Этот процесс может занять некоторое время, вы сможете проверить изменения на вашем сайте через несколько минут.</small><br>
                        <div class="clearfix"></div><br>
                        <button type="submit" class="btn btn-primary waves-effect waves-light m-t-20" id="delete-btn">Создать фейковые данные</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<script>
    $(function() {
        var generate_form = $('form.generate-form');
        generate_form.ajaxForm({
            url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=fake-users&p=fake-users',
            beforeSend: function() {
                $('#delete-btn').text('Пожалуйста, подождите...');
            },
            success: function(data) {
                if (data.status == 200) {
                    $('#delete-btn').text('Пользователи создаются, проверьте ваш сайт через несколько минут.');
                    setTimeout(function () {
                        $('#delete-btn').text('Создать фейковые данные');
                    }, 4000);
                }
            }
        });

    });
</script>
