<?php
$social_media_links_on = ($wo['config']['social_media_links'] == 'on') ? 'checked' : '';
$social_media_links_off = ($wo['config']['social_media_links'] == 'off') ? 'checked' : '';
?>
<div class="container-fluid">
    <div>
        <h3>Настройки сайта</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Главная</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Настройки</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Настройки сайта</li>
            </ol>
        </nav>
    </div>
    <!-- Вертикальная компоновка -->
    <div class="row">
        <div class="col-lg-6 col-md-6 float-left">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Настройки веб-сайта</h6>
                    <div class="site-settings-alert"></div>
                    <form class="site-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Заголовок веб-сайта</label>
                                <input type="text" id="default_title" name="default_title" class="form-control" value="<?php echo $wo['config']['default_title']; ?>">
								<small class="admin-info">Основной заголовок вашего веб-сайта, он будет отображаться в Google и на вкладке браузера.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Имя веб-сайта</label>
                                <input type="text" id="site_name" name="site_name" class="form-control" value="<?php echo $wo['config']['site_name']; ?>">
								<small class="admin-info">Имя вашего веб-сайта, будет отображаться в футере и в E-mail сообщениях.</small>
                            </div>
                        </div>

                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Ключевые слова веб-сайта</label>
                                <input type="text" id="meta_keywords" name="meta_keywords" class="form-control" value="<?php echo $wo['config']['meta_keywords']; ?>">
								<small class="admin-info">Ключевые слова вашего веб-сайта, используются для SEO и поисковых систем.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Описание веб-сайта</label>
                                <textarea name="meta_description" id="meta_description" class="form-control" cols="30" rows="5"><?php echo $wo['config']['meta_description']; ?></textarea>
								<small class="admin-info">Описание вашего веб-сайта, используется для SEO и поисковых систем. Рекомендуется максимум 100 символов.</small>
                            </div>
                        </div>

                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Серверный ключ веб-сайта</label>
                                <input type="text" id="skey" name="skey" class="form-control" value="<?php global $serverkey;
echo $serverkey; ?>">
								<small class="admin-info">Используется для подключения API, в основном для приложений Android/iOS.</small>
                            </div>
                        </div>
                        <hr>
                        <div>
                            <div class="float-left">
                                <label for="social_media_links" class="main-label">Показывать ссылки на соцсети</label>
                                <br><small class="admin-info">Отображать ссылки на социальные сети в футере.</small>
                            </div>
                            <div class="form-group float-right switcher">
                                <input type="hidden" name="social_media_links" value="off">
                                <input type="checkbox" name="social_media_links" id="social_media_links-enabled" value="on" <?php echo $social_media_links_on; ?>>
                                <label for="social_media_links-enabled" class="check-trail"><span class="check-handler"></span></label>
                            </div>
                            <div class="clearfix"></div>
                            <hr>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Facebook</label>
                                <input type="text" id="facebook_url" name="facebook_url" class="form-control" value="<?php echo $wo['config']['facebook_url']; ?>">
								<small class="admin-info">Ссылка на вашу страницу в Facebook, отображается в футере.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Twitter</label>
                                <input type="text" id="twitter_url" name="twitter_url" class="form-control" value="<?php echo $wo['config']['twitter_url']; ?>">
								<small class="admin-info">Ссылка на вашу страницу в Twitter, отображается в футере.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Google</label>
                                <input type="text" id="google_url" name="google_url" class="form-control" value="<?php echo $wo['config']['google_url']; ?>">
								<small class="admin-info">Ссылка на вашу страницу в Google, отображается в футере.</small>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                         <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Код Google Tag/Analytics</label>
                                <textarea name="google_tag_code" id="google_tag_code" class="form-control" cols="30" rows="5"><?php echo openssl_decrypt($wo['config']['google_tag_code'], "AES-128-ECB", 'mysecretkey1234'); ?></textarea>
                            </div>
                            <small>Вставьте полный код Google Analytics для отслеживания трафика.</small>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Приложения для Android и iOS</h6>
                    <div class="api-settings-alert"></div>
                    <form class="api-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Ссылка на Native Android</label>
                                <input type="text" id="native_android_url" name="native_android_url" class="form-control" value="<?php echo $wo['config']['native_android_url']; ?>">
                                <small class="admin-info">Ссылка на ваше приложение Native Android.</small>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Ссылка на Native iOS</label>
                                <input type="text" id="native_ios_url" name="native_ios_url" class="form-control" value="<?php echo $wo['config']['native_ios_url']; ?>">
                                <small class="admin-info">Ссылка на ваше приложение Native iOS.</small>
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- Конец вертикальной компоновки -->

<script>
    $(function() {
    $('.switcher input[type=checkbox]').click(function () {
        var configName = $(this).attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        if ($(this).is(":checked") === true) {
            objData[configName] = $(this).val();
        }
        else{
            if ($('input[name='+configName+']')[0]) {
                objData[configName] = $($('input[name='+configName+']')[0]).val();
            }
        }
        objData['hash_id'] = hash_id;
        $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData);
    });

    var setTimeOutColor = setTimeout(function (){});
    $('select').on('change', function() {
         clearTimeout(setTimeOutColor);
        var thisElement = $(this);
        var configName = thisElement.attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        objData[configName] = this.value;
        objData['hash_id'] = hash_id;
        thisElement.addClass('warning');
        $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function (data) {
            if (data.status == 200) {
                thisElement.removeClass('warning');
                thisElement.addClass('success');
            } else {
                thisElement.addClass('error');
            }
            var setTimeOutColor = setTimeout(function () {
                thisElement.removeClass('success');
                thisElement.removeClass('warning');
                thisElement.removeClass('error');
            }, 2000);
        });
    });
    $('input[type=text], input[type=number], textarea').on('input', delay(function() {
            clearTimeout(setTimeOutColor);
            var thisElement = $(this);
            var configName = thisElement.attr('name');
            var hash_id = $('input[name=hash_id]').val();
            var objData = {};
            objData[configName] = this.value;
            objData['hash_id'] = hash_id;
            thisElement.addClass('warning');
            if (configName == 'google_tag_code') {
               objData[configName] = btoa(this.value);
            }
            $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function (data) {
                if (data.status == 200) {
                    thisElement.removeClass('warning');
                    thisElement.addClass('success');
                } else {
                    thisElement.addClass('error');
                }
                var setTimeOutColor = setTimeout(function () {
                    thisElement.removeClass('success');
                    thisElement.removeClass('warning');
                    thisElement.removeClass('error');
                }, 2000);
                //thisElement.focus();
            });
    }, 500));
});
</script>
